In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
dp=pd.read_csv('FastagFraudDetection.csv')

In [3]:
dp.head()

Transaction_ID       Timestamp Vehicle_Type         FastagID TollBoothID  \
0               1  1/6/2023 11:20         Bus   FTG-001-ABC-121       A-101   
1               2  1/7/2023 14:55          Car  FTG-002-XYZ-451       B-102   
2               3  1/8/2023 18:25   Motorcycle              NaN       D-104   
3               4   1/9/2023 2:05        Truck  FTG-044-LMN-322       C-103   
4               5  1/10/2023 6:35          Van  FTG-505-DEF-652       B-102   

  Lane_Type Vehicle_Dimensions  Transaction_Amount  Amount_paid  \
0   Express              Large                 350          120   
1   Regular              Small                 120          100   
2   Regular              Small                   0            0   
3   Regular              Large                 350          120   
4   Express             Medium                 140          100   

                   Geographical_Location  Vehicle_Speed Vehicle_Plate_Number  \
0  13.059816123454882, 77.77068662374292             65           KA11AB1234   
1  13.059816123454882, 77.77068662374292             78           KA66CD5678   
2  13.059816123454882, 77.77068662374292             53           KA88EF9012   
3  13.059816123454882, 77.77068662374292             92           KA11GH3456   
4  13.059816123454882, 77.77068662374292             60           KA44IJ6789   

  Fraud_indicator  
0           Fraud  
1           Fraud  
2       Not Fraud  
3           Fraud  
4           Fraud

In [4]:
dp.shape

(5000, 13)

In [5]:
dp.describe()

Transaction_ID  Transaction_Amount  Amount_paid  Vehicle_Speed
count     5000.000000          5000.00000  5000.000000    5000.000000
mean      2500.500000           161.06200   141.261000      67.851200
std       1443.520003           112.44995   106.480996      16.597547
min          1.000000             0.00000     0.000000      10.000000
25%       1250.750000           100.00000    90.000000      54.000000
50%       2500.500000           130.00000   120.000000      67.000000
75%       3750.250000           290.00000   160.000000      82.000000
max       5000.000000           350.00000   350.000000     118.000000

In [26]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Transaction_ID         5000 non-null   int64 
 1   Timestamp              5000 non-null   object
 2   Vehicle_Type           5000 non-null   object
 3   FastagID               4451 non-null   object
 4   TollBoothID            5000 non-null   object
 5   Lane_Type              5000 non-null   object
 6   Vehicle_Dimensions     5000 non-null   object
 7   Transaction_Amount     5000 non-null   int64 
 8   Amount_paid            5000 non-null   int64 
 9   Geographical_Location  5000 non-null   object
 10  Vehicle_Speed          5000 non-null   int64 
 11  Vehicle_Plate_Number   5000 non-null   object
 12  Fraud_indicator        5000 non-null   object
dtypes: int64(4), object(9)
memory usage: 507.9+ KB


In [6]:
dp['Fraud_indicator'].value_counts

<bound method IndexOpsMixin.value_counts of 0           Fraud
1           Fraud
2       Not Fraud
3           Fraud
4           Fraud
          ...    
4995    Not Fraud
4996    Not Fraud
4997    Not Fraud
4998    Not Fraud
4999        Fraud
Name: Fraud_indicator, Length: 5000, dtype: object>

In [7]:
dp.tail()

Transaction_ID        Timestamp Vehicle_Type         FastagID  \
4995            4996   1/1/2023 22:18        Truck  FTG-445-EDC-765   
4996            4997  1/17/2023 13:43          Van  FTG-446-LMK-432   
4997            4998    2/5/2023 5:08        Sedan  FTG-447-PLN-109   
4998            4999  2/20/2023 20:34          SUV  FTG-458-VFR-876   
4999            5000   3/10/2023 0:59         Bus   FTG-459-WSX-543   

     TollBoothID Lane_Type Vehicle_Dimensions  Transaction_Amount  \
4995       C-103   Regular              Large                 330   
4996       B-102   Express             Medium                 125   
4997       A-101   Regular             Medium                 115   
4998       B-102   Express              Large                 145   
4999       C-103   Regular              Large                 330   

      Amount_paid                 Geographical_Location  Vehicle_Speed  \
4995          330  13.21331620748757, 77.55413526894684             81   
4996          125  13.21331620748757, 77.55413526894684             64   
4997          115  13.21331620748757, 77.55413526894684             93   
4998          145  13.21331620748757, 77.55413526894684             57   
4999          125  13.21331620748757, 77.55413526894684             86   

     Vehicle_Plate_Number Fraud_indicator  
4995           KA74ST0123       Not Fraud  
4996           KA38UV3456       Not Fraud  
4997           KA33WX6789       Not Fraud  
4998           KA35YZ0123       Not Fraud  
4999           KA37AB3456           Fraud

In [8]:
x=dp.drop(['Fraud_indicator','Timestamp','Vehicle_Type','FastagID','TollBoothID','Lane_Type','Vehicle_Dimensions','Geographical_Location','Vehicle_Plate_Number'],axis=1)
y=dp['Fraud_indicator']

In [9]:
print(x)
print(y)

      Transaction_ID  Transaction_Amount  Amount_paid  Vehicle_Speed
0                  1                 350          120             65
1                  2                 120          100             78
2                  3                   0            0             53
3                  4                 350          120             92
4                  5                 140          100             60
...              ...                 ...          ...            ...
4995            4996                 330          330             81
4996            4997                 125          125             64
4997            4998                 115          115             93
4998            4999                 145          145             57
4999            5000                 330          125             86

[5000 rows x 4 columns]
0           Fraud
1           Fraud
2       Not Fraud
3           Fraud
4           Fraud
          ...    
4995    Not Fraud
4996    Not Fraud
499

In [10]:
scaler=StandardScaler()

In [11]:
scaler.fit(x)

StandardScaler()

In [12]:
sd=scaler.transform(x)

In [13]:
x=sd
y=dp['Fraud_indicator']

In [14]:
print(x)
print(y)

[[-1.73170443  1.68036444 -0.1996894  -0.17180161]
 [-1.73101161 -0.36519453 -0.38753513  0.61152502]
 [-1.73031879 -1.43244269 -1.32676377 -0.89487234]
 ...
 [ 1.73031879 -0.40966321 -0.24665083  1.51536343]
 [ 1.73101161 -0.14285117  0.03511776 -0.65384876]
 [ 1.73170443  1.50248975 -0.15272797  1.09357217]]
0           Fraud
1           Fraud
2       Not Fraud
3           Fraud
4           Fraud
          ...    
4995    Not Fraud
4996    Not Fraud
4997    Not Fraud
4998    Not Fraud
4999        Fraud
Name: Fraud_indicator, Length: 5000, dtype: object


TRAIN TEST SPLIT

In [15]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [16]:
print(x.shape,x_test.shape,x_train.shape)

(5000, 4) (4000, 4) (1000, 4)


TRAINING THE MODEL

In [17]:
classifer=svm.SVC(kernel='linear')


TRAINING THE SVM CLASSIFIER

In [18]:
classifer.fit(x_train,y_train)

SVC(kernel='linear')

MODEL EVALUATION

In [19]:
#ACCURACY SCORE ON THE TRAINING DATA
x_train_prediction=classifer.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)



In [20]:
print("accuracy score of training data is : ",training_data_accuracy)

accuracy score of training data is :  0.984


In [21]:
#ACCURACY SCORE ON THE TEST DATA
x_test_prediction=classifer.predict(x_test)
test_data_accuracy=accuracy_score(x_test_prediction,y_test)


In [22]:
print("accuracy score of test data is : ",test_data_accuracy)

accuracy score of test data is :  0.98475


PREDICTIVE SYSTEM

In [24]:
#METHOD-1
input_data=(1,350,120,65)

#changing the input data into numpy array
input_data_asnumpy_arr=np.asarray(input_data)

#reshape the array as we are predicting for 1 instance
input_data_reshaped=input_data_asnumpy_arr.reshape(1,-1)

#standardize the input data
std_data=scaler.transform(input_data_reshaped)

prediction=classifer.predict(std_data)
print(prediction)

['Fraud']


c:\Users\Pratham Bisht\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [25]:
#METHOD-2
input_data=[[1,350,120,65]]

prediction=classifer.predict(input_data)
print(prediction)

['Fraud']
